// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: AssemblyTitle("MyBatis.Migrations")>]
[<assembly: AssemblyProduct("MyBatis.NET")>]
[<assembly: AssemblyDescription("")>]
[<assembly: AssemblyCompany("http://ibatis.apache.org/")>]
[<assembly: AssemblyCopyright("Copyright © 2009-2018 http://ibatis.apache.org/.")>]
[<assembly: AssemblyTrademark("Licensed under the Apache License, Version 2.0")>]
[<assembly: AssemblyConfiguration("Debug")>]
[<assembly: AssemblyCulture("")>]
[<assembly: AssemblyVersion("1.6.6858.23793")>]
[<assembly: AssemblyFileVersion("1.6.6858.23793")>]
[<assembly: AssemblyInformationalVersion("1.6.6858.23793")>]
do()
